#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

xsetroot -cursor_name left_ptr &

#bspc rule -a firefox state=floating
bspc rule -a Chromium desktop='^2'
bspc rule -a firefox desktop='^2' follow=on
bspc rule -a Steam desktop='^3' follow=on state=floating
bspc rule -a Spotify state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
bspc rule -a discord desktop='^4'
